version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.22.5
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f89df3a2-679b-4112-8191-4f0c9cbd3b4e"
      - checkout
      # 使用node_modules缓存
      - restore_cache:
          keys:
            - node_dependencies
      - run:
          name: Install
          command: npm install
      # 对node_modules 进行缓存
      - save_cache:
          paths:
            - node_modules
          key: node_dependencies
      - run:
          name: Build
          command: npm run docs:build
      - run:
          name: Auth Deploy
          # 设置文件权限
          command: chmod +x scripts/deploy.sh
      - run:
          name: Deploy
          # 执行shell脚本
          command: ./scripts/deploy.sh
